# Generated by Django 3.0.1 on 2019-12-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20191230_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='appleArtist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='spotifyArtist',
        ),
        migrations.AddField(
            model_name='artist',
            name='appleArtist',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotifyArtist',
            field=models.URLField(null=True),
        ),
    ]
