# Generated by Django 3.0.1 on 2020-01-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_contentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='partners',
            new_name='platforms',
        ),
        migrations.RenameModel(
            old_name='Partner',
            new_name='Platform',
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.IntegerField()),
                ('download', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Platform')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Track')),
            ],
        ),
    ]
