# Generated by Django 3.0.1 on 2019-12-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OtherArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.IntegerField(choices=[(None, '(Unknown)'), (0, 'Single'), (1, 'EP'), (2, 'Album')])),
                ('title', models.CharField(max_length=150)),
                ('artwork', models.ImageField(upload_to='')),
                ('genre', models.CharField(max_length=50)),
                ('subgenre', models.CharField(max_length=50, null=True)),
                ('appleArtist', models.URLField(null=True)),
                ('spotifyArtist', models.URLField(null=True)),
                ('recordLabel', models.CharField(max_length=150)),
                ('releaseDate', models.DateField()),
                ('OtherArtists', models.ManyToManyField(related_name='otherArtists_set', to='panel.OtherArtist')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Artist')),
                ('partners', models.ManyToManyField(related_name='partners_set', to='panel.Partner')),
                ('tracks', models.ManyToManyField(related_name='tracks_set', to='panel.Track')),
            ],
        ),
    ]
