# Generated by Django 3.0.1 on 2020-01-21 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherartist',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='otherartist_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
