# Generated by Django 3.0.1 on 2019-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20191230_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('status', models.IntegerField(choices=[(None, 'Please Select...'), (0, 'Pending'), (1, 'Removal Request Received')])),
            ],
        ),
    ]
