# Generated by Django 3.0.2 on 2020-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.IntegerField(choices=[(None, 'Please Select...'), (0, 'Pending'), (1, 'Statement Recieved')], default=0),
        ),
    ]
