# Generated by Django 3.0.2 on 2020-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_statement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.IntegerField(choices=[(None, 'Please Select...'), (0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
