# Generated by Django 3.0.2 on 2020-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_album_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork',
            field=models.ImageField(upload_to='media/cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.IntegerField(choices=[(None, 'Please Select...'), (0, 'Pending'), (1, 'in Progress'), (2, 'Confirmed'), (3, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='appleArtist',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotifyArtist',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='OtherArtists',
            field=models.ManyToManyField(blank=True, related_name='otherArtists_set', to='panel.OtherArtist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='media',
            field=models.FileField(upload_to='tracks'),
        ),
    ]
