# Generated by Django 3.0.1 on 2020-01-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0005_auto_20200102_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
