# Generated by Django 3.0.2 on 2020-01-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20200125_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='number',
        ),
    ]
