# Generated by Django 3.0.2 on 2020-02-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_announcement_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='subgenre',
        ),
    ]
