# Generated by Django 3.0.2 on 2020-02-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20200201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Genre'),
        ),
    ]
