# Generated by Django 3.0.2 on 2020-02-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(None, 'Please Select...'), (0, 'Pending'), (1, 'Statement Recieved')], default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Track')),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='splits',
            field=models.ManyToManyField(related_name='split_set', to='panel.SplitStatement'),
        ),
    ]
