# Generated by Django 3.0.2 on 2020-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20200204_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='recordLabel',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_label',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
