# Generated by Django 3.0.2 on 2020-02-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20200206_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='recordLabel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.RecordLabel'),
        ),
    ]
